input.onButtonPressed(Button.A, function () {
    DFRobotMaqueenPlus.mototRun(Motors.M1, Dir.CW, 50)
    DFRobotMaqueenPlus.mototRun(Motors.M2, Dir.CCW, 50)
    basic.pause(1800)
    DFRobotMaqueenPlus.mototStop(Motors.ALL)
    DFRobotMaqueenPlus.mototRun(Motors.M2, Dir.CW, 50)
    DFRobotMaqueenPlus.mototRun(Motors.M1, Dir.CCW, 50)
    basic.pause(1800)
    DFRobotMaqueenPlus.mototStop(Motors.ALL)
    DFRobotMaqueenPlus.mototRun(Motors.ALL, Dir.CW, 37)
    basic.pause(2000)
    DFRobotMaqueenPlus.mototRun(Motors.ALL, Dir.CCW, 37)
    basic.pause(2000)
    DFRobotMaqueenPlus.mototStop(Motors.ALL)
})
DFRobotMaqueenPlus.I2CInit()
